workbench:
  title: jank

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jank?allowMultiQueries=true
      username: root
      password: root
      filters: false
      connectionProperties: config.decrypt=false
      initialSize: 50
      minIdle: 50
      maxActive: 200
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
  http:
      multipart:
          maxFileSize: 100Mb
          maxRequestSize: 1000Mb
  thymeleaf:
      mode: HTML5
      cache: false
      encoding: UTF-8
      content-type: text/html

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/jank/orm/mapper/*.xml
  type-aliases-package: com.jank.orm.entity

server:
  #maxHttpHeaderSize: 8192
  context-path: /
  port: 8080

#  redis:
#    host: 124.202.155.72
#    port: 61001
#    password: skycloud@123
#    database: 8
#    pool:
#      max-active: 20
#      max-idle: 10
#      min-idle: 10
#      max-wait: 3000